### ISSUE TITLE
i will find you and i will kill you

### ISSUE THREAD

**Issue by FDSoftware** [MaquinolaNet/Maquinola.net#2]
a menos que me escribas en telegram a => FDSoftware  Polsaker dice que te extraña
![image](https://user-images.githubusercontent.com/15681280/80779688-ca846c80-8b42-11ea-9402-b8e25f5f7bae.png)

**Comment by andreuscafe** [comment]
Hola vi que participaste en la discusión del repo así que te agrego a la organización ya que pareces un buen colaborador. Saludos.

**Comment by fermino** [comment]
Este issue parece resuelto ya que el susodicho se dignó aparecer. Lo cierro, cualquier cosa si desaparece el sujeto me comentan de nuevo. Abrazos.
