### ISSUE TITLE
Falta el repo

### ISSUE THREAD

**Issue by andreuscafe** [MaquinolaNet/Maquinola.net#3]
Estuve revisando este repo y vi que falta subir el código, ¿para cuándo lo podes tener @fermino? Te lo asigno así no se te olvida cuando le quisimos cobrar 30 lucas a dino por un buscador de reviews de electrodomésticos hace unos 5-6 años, o cuando hicimos la juntada con @Polsaker en Rosario y una gitana casi nos afana y comí chipa con tierra en un bondi rumbo al pueblo donde te guarecías con tu orquesta. Tengo los videos todavía. Aparecé o los publico.

Abrazo. SUBÍ EL CÓDIGO PEDAZO DE MIERDA.

**Comment by fermino** [comment]
JAJAJAJA Que brutalidad esta, no tengo TG pero ahí te escribo
